### ISSUE TITLE
ANTs resample image utility gear

### ISSUE THREAD

**Issue by jskim628** [EmotionCognitionLab/flywheel#54]
<img width="623" alt="Screenshot 2024-07-12 at 2 56 09 PM" src="https://github.com/user-attachments/assets/49e3342f-4ba6-415f-8ee4-03a6c66b8912">

When running the ANTs resample image utility gear, it doesn't work if the acqusition has other files in addition to the NIFTI. It gives me an ambiguous input error.

**Comment by noah10** [comment]
This should be fixed with v0.0.5_2.5.0. Please test it and close this issue if it has addressed the problem.

**Comment by noah10** [comment]
Martina reports that this works as expected (as long as no acquisition itself has more than one nifti file, of course).
