### ISSUE TITLE
SuperBet2 does not work on fast spin echo data

### ISSUE THREAD

**Issue by md06451** [EmotionCognitionLab/flywheel#58]
Hi Noah I tried, SuperBet2 on fast spin echo (FSE) data but it fails (see fsl-superbet2_Try_SkullStrip_FSE)
INstead it works on whole brain data:  https://uscdni.flywheel.io/#/projects/6615ba1626fa7095f409418d/sessions/66870c0cf7cdcb78af9494c3?subjectTab=session&tab=analyses
https://uscdni.flywheel.io/#/projects/6615ba1626fa7095f409418d/sessions/67172c5469393b5ba92a8ad8?subjectTab=session&tab=data

on my machine bet works for FSE data.

**Comment by noah10** [comment]
Can you try BET2 on your machine and see if that works for FSE data? That will help me know whether we should install a BET gear or ask Flywheel to make the BET2 gear work with FSE data.

**Comment by noah10** [comment]
OK - so it sounds like you'd rather have a BET gear than have the BET2 gear work with FSE data?

**Comment by md06451** [comment]
yes I think so

**Comment by md06451** [comment]
@noah10 I manage to find a way out from skull-stripping the data. So this step will not be necessary. I will close the issue
