### ISSUE TITLE
Extract weight and height data 

### ISSUE THREAD

**Issue by md06451** [EmotionCognitionLab/flywheel#59]
Hi Noah, 
would it be possible to extract patient size and PatientWeight from https://uscdni.flywheel.io/#/projects/6699964447af406d67fc4c33.    We would need to save the data in .xslx file. 
Formula to transform meters in inches: 1m = 1x 39.3701
Formula to transform kg in lb: = 1 kg = 2.20462262185 lb
We need this only for some participants/sessions.  Attached the list: 
[VASC_overview_ID_sessions.xlsx](https://github.com/user-attachments/files/17907557/VASC_overview_ID_sessions.xlsx)
This is more important than denoising gear.

**Comment by noah10** [comment]
This has been addressed with Data Views.
